server:
  port: 9001

spring:
  application:
    name: gateway-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

zuul:
  prefix: zero
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000