server:
  port: 9001

spring:
  application:
    name: gateway-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  routes:
    # 博客服务
    blog:
      path: /blog/**
      serviceId: zero-blog
      strip-prefix: false


ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000